In [5]:
import numpy as np

In [155]:
#1 The Odd Ones Out

arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
OddArr = np.all(arr % 2 == 1, axis=1)
# Filter the array using the mask
FinList = arr[OddArr]

print(FinList)

[[5 7 9]
 [7 7 7]]


In [23]:
#2 Let's Play Checkers! - 2.1

checkerboard_0 = np.zeros((8,8))
print(checkerboard_0)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [115]:
#2.2

checkerboard = np.ones((8,8))
checkerboard[1::2, ::2] = 0
checkerboard[::2, 1::2] = 0
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [121]:
#2.3

checkerboard = np.ones((8,8))
checkerboard[1::2, ::2] = 0
checkerboard[::2, 1::2] = 0
print(checkerboard)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [35]:
#2.4

checkerboard = np.ones((3,3))
checkerboard = np.zeros((8,8))
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [153]:
#3 The Expanding Universe

def universe(string, numofspaces):
    charr = np.array(list(string))
    sparr = np.array([' ' * numofspaces] * (len(string) - 1))
    stringfinal = np.char.add(charr[:-1], sparr)
    finish = ''.join(stringfinal) + charr[-1]

    return finish 

expansion = universe("galaxy, clusters", 5)
print(expansion)

g     a     l     a     x     y     ,           c     l     u     s     t     e     r     s


In [159]:
#4

def SecondLargest(arr):
    SecondLargestArr = np.sort(arr, axis=0)[::-1]
    
    return SecondLargestArr[1]

arr = np.array([[192, 898, 747, 692, 914],
                [849, 249, 370, 658, 451],
                [802, 785, 143, 198, 616],
                [696, 926, 269, 788, 642],
                [583, 372, 468, 899, 911]])
                
planets = SecondLargest(arr)
print(planets)

[802 898 468 788 911]
